// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUcsJa_iVGksNJOj0bRySLtTwggtkUdYM',
    appId: '1:38405725917:web:459b6d5230b6e7b9c10534',
    messagingSenderId: '38405725917',
    projectId: 'aplikasi-inventaris-cb59a',
    authDomain: 'aplikasi-inventaris-cb59a.firebaseapp.com',
    storageBucket: 'aplikasi-inventaris-cb59a.firebasestorage.app',
    measurementId: 'G-PB9LRBTT9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1PBB34472KKT1BimOBSEkbZxPyquH-mk',
    appId: '1:38405725917:android:3aded3063f7a0febc10534',
    messagingSenderId: '38405725917',
    projectId: 'aplikasi-inventaris-cb59a',
    storageBucket: 'aplikasi-inventaris-cb59a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrLwaXyx79a0-NyQW75VF0W8cessjHEXc',
    appId: '1:38405725917:ios:a07eabde207d95b7c10534',
    messagingSenderId: '38405725917',
    projectId: 'aplikasi-inventaris-cb59a',
    storageBucket: 'aplikasi-inventaris-cb59a.firebasestorage.app',
    iosBundleId: 'com.example.lab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrLwaXyx79a0-NyQW75VF0W8cessjHEXc',
    appId: '1:38405725917:ios:a07eabde207d95b7c10534',
    messagingSenderId: '38405725917',
    projectId: 'aplikasi-inventaris-cb59a',
    storageBucket: 'aplikasi-inventaris-cb59a.firebasestorage.app',
    iosBundleId: 'com.example.lab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUcsJa_iVGksNJOj0bRySLtTwggtkUdYM',
    appId: '1:38405725917:web:79cc828f256b85f4c10534',
    messagingSenderId: '38405725917',
    projectId: 'aplikasi-inventaris-cb59a',
    authDomain: 'aplikasi-inventaris-cb59a.firebaseapp.com',
    storageBucket: 'aplikasi-inventaris-cb59a.firebasestorage.app',
    measurementId: 'G-4QW8YSYGXQ',
  );
}
